site_name: Urban Heat Technical Manual
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - toc.follow

nav:
  - Home: index.md
  - Introduction: introduction.md
  - Data Requirements: Data-Requirements.md
  - Methodology:
      - Extract & Clip Data: methodology/section1-extract-clip.md
      - Spatial Joins: methodology/section2-spatial-joins.md
      - Heat Risk Score: methodology/section3-heat-risk-score.md
      - 3-30-300 Compliance: methodology/section4-3-30-300.md
  - Recommendations for Replication: recommendations.md
  - References & Data Licensing: references.md

