site_name: Urban Heat Technical Manual
site_description: >
  Technical manual and replication guide for the Urban Heat and 3-30-300
  analysis in Nairobi.

repo_url: https://github.com/sakinamammad/Urban-Heat-Technical-Manual
repo_name: Urban-Heat-Technical-Manual

theme:
  name: readthedocs

nav:
  - Welcome: index.md
  - Authors: index.md#authors
  - Introduction:
      - "Purpose of the Codebook": introduction.md#purpose-of-the-codebook
      - "Overview of the Project": introduction.md#overview-of-the-project
      - "Targeted Stakeholders": introduction.md#targeted-stakeholders
      
  - "Data Requirements & Structure": 
      - Data Requirements: data-requirements.md
  
  - "Methodology and Replication":
      - "Step 0: Extracting and Preparing Input Data": methodology.md#step-0-extracting-and-preparing-input-data
      - "Step 1: Measuring Heat (SUHII)": methodology.md#step-1-measuring-heat---urban-heat-island-effect
      - "Step 2: Social Vulnerability": methodology.md#step-2-social-vulnerability
      - "Step 3: Holistic Heat Risk": methodology.md#step-3-calculating-holistic-heat-risk
      - "Step 4: 3-30-300 Improvement": methodology.md#step-4-identifying-areas-needing-3-30-300-improvement
      - "Dashboard Development (Optional for Analysis)": methodology.md#dashboard-development-optional-for-analysis
  - "Limitations and Future Work":
      - Limitations: limitations.md#limitations
      - Future Work: limitations.md#future-work

      
  - "References and Data Licensing":
      - References: references.md


